# Generated by Django 3.2.4 on 2021-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Graphic Design', 'Graphic Design'), ('Tech Gadget', 'Tech Gadget'), ('Other', 'Other')], max_length=300, null=True)),
                ('body', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('date', models.DateField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='CategoryIndexTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
    ]
