# Generated by Django 3.2.4 on 2021-06-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='madmincategory',
            options={'verbose_name': 'MadminCategory', 'verbose_name_plural': 'MadminCategories'},
        ),
    ]
