# Generated by Django 3.2.4 on 2021-06-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_madmincategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madmincategory',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
