# Generated by Django 3.2.4 on 2021-06-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210620_0630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='CategoryIndexTitle',
        ),
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
    ]
